language: node_js
node_js:
- 8.11.1
branches:
   only:
      - master
before_script:
   - npm install -g firebase-tools
   - npm install -g @angular/cli
script:
- ng build --prod --aot
after_success:
   - firebase deploy --token $FIREBASE_TOKEN